services:
  - type: web
    name: InsightsT
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # REMOVA esta linha do frontend se for só backend:
      # cd frontend && npm install && npm run build
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: analise_db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true